*DECK LCMGCL
      SUBROUTINE LCMGCL(IPLIST,ISET,ILONG,HDATA)
*
*-----------------------------------------------------------------------
*
* COPY A CHARACTER VARIABLE FROM A LIST INTO MEMORY.
*
* INPUT PARAMETERS:
*  IPLIST : ADDRESS OF THE TABLE.
*    ISET : POSITION OF THE BLOCK IN THE LIST.
*   ILONG : DIMENSION OF THE CHARACTER VARIABLE.
*
* OUTPUT PARAMETER:
*   HDATA : CHARACTER VARIABLE. CHARACTER*(*) HDATA(ILONG)
*
*------------------------------------- AUTHOR: A. HEBERT ; 23/04/00 ----
*
      USE GANLIB
*----
*  SUBROUTINE ARGUMENTS
*----
      TYPE(C_PTR) IPLIST
      INTEGER ISET,ILONG
      CHARACTER*(*) HDATA(ILONG)
*----
*  LOCAL VARIABLES
*----
      TYPE(C_PTR) JPLIST
      INTEGER, ALLOCATABLE, DIMENSION(:) :: IDATA
*
      ILE1=(LEN(HDATA(1))+3)/4
      CALL LCMLEL(IPLIST,ISET,JLONG,ITYLCM)
      IF(ITYLCM.NE.10) CALL XABORT('LCMGCD: LIST EXPECTED.')
      IF(JLONG.GT.ILONG) CALL XABORT('LCMGCD: HDATA OVERFLOW.')
      JPLIST=LCMLIL(IPLIST,ISET,JLONG)
      DO JSET=1,ILONG
         CALL LCMLEL(JPLIST,JSET,ILE2,ITYLCM)
         IF(ITYLCM.NE.3) CALL XABORT('LCMGCL: CHARACTER EXPECTED.')
         ALLOCATE(IDATA(ILE2))
         CALL LCMGDL(JPLIST,JSET,IDATA)
         HDATA(JSET)=' '
         WRITE(HDATA(JSET),'(100A4)') (IDATA(I),I=1,MIN(ILE1,ILE2))
         DEALLOCATE(IDATA)
      ENDDO
      DO ISET=JLONG+1,ILONG
         HDATA(ISET)=' '
      ENDDO
      RETURN
      END
