*DECK LCMPCL
      SUBROUTINE LCMPCL(IPLIST,ISET,ILONG,HDATA)
*
*-----------------------------------------------------------------------
*
* COPY A CHARACTER VARIABLE FROM MEMORY INTO A LIST.
*
* INPUT PARAMETERS:
*  IPLIST : ADDRESS OF THE TABLE.
*    ISET : POSITION OF THE BLOCK IN THE LIST.
*   ILONG : DIMENSION OF THE CHARACTER VARIABLE.
*   HDATA : CHARACTER VARIABLE. CHARACTER*(*) HDATA(ILONG)
*
*------------------------------------- AUTHOR: A. HEBERT ; 23/04/00 ----
*
      USE GANLIB
*----
*  SUBROUTINE ARGUMENTS
*----
      TYPE(C_PTR) IPLIST
      INTEGER ISET,ILONG
      CHARACTER*(*) HDATA(*)
*----
*  LOCAL VARIABLES
*----
      TYPE(C_PTR) JPLIST
      INTEGER, ALLOCATABLE, DIMENSION(:) :: IDATA
*
      ILEN=(LEN(HDATA(1))+3)/4
      IF(ILEN.GT.100) CALL XABORT('LCMPCL: ILEN OVERFLOW.')
      ALLOCATE(IDATA(ILEN))
      JPLIST=LCMLIL(IPLIST,ISET,ILONG)
      DO JSET=1,ILONG
         READ(HDATA(JSET),'(100A4)') (IDATA(I),I=1,ILEN)
         CALL LCMPDL(JPLIST,JSET,ILEN,3,IDATA)
      ENDDO
      DEALLOCATE(IDATA)
      RETURN
      END
