*DECK LCMPCD
      SUBROUTINE LCMPCD(IPLIST,NAMP,ILONG,HDATA)
*
*----------------------------------------------------------------------
*
* COPY A CHARACTER VARIABLE FROM MEMORY INTO A TABLE.
*
* INPUT PARAMETERS:
*  IPLIST : ADDRESS OF THE TABLE.
*    NAMP : CHARACTER*12 NAME OF THE BLOCK.
*   ILONG : DIMENSION OF THE CHARACTER VARIABLE.
*   HDATA : CHARACTER VARIABLE. CHARACTER*(*) HDATA(ILONG)
*
*------------------------------------- AUTHOR: A. HEBERT ; 12/03/00 ---
*
      USE GANLIB
*----
*  SUBROUTINE ARGUMENTS
*----
      TYPE(C_PTR) IPLIST
      INTEGER ILONG
      CHARACTER*(*) NAMP,HDATA(*)
*----
*  LOCAL VARIABLES
*----
      TYPE(C_PTR) JPLIST
      INTEGER, ALLOCATABLE, DIMENSION(:) :: IDATA
*
      ILEN=(LEN(HDATA(1))+3)/4
      IF(ILEN.GT.100) CALL XABORT('LCMPCD: ILEN OVERFLOW.')
      ALLOCATE(IDATA(ILEN))
      JPLIST=LCMLID(IPLIST,NAMP,ILONG)
      DO ISET=1,ILONG
         READ(HDATA(ISET),'(100A4)') (IDATA(I),I=1,ILEN)
         CALL LCMPDL(JPLIST,ISET,ILEN,3,IDATA)
      ENDDO
      DEALLOCATE(IDATA)
      RETURN
      END
